/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
 */

package main

import "fmt"

func findTheDifference(s string, t string) byte {
	dictS := make(map[byte]int)
	for _, v := range s {
		dictS[byte(v)]++
	}
	for _, v := range t {
		if dictS[byte(v)] == 0 {
			return byte(v)
		} else {
			dictS[byte(v)]--
		}
	}
	return '0'
}

func main() {
	fmt.Println(findTheDifference("a", "aa"))
}
